msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-08-13 12:20+0000\n"
"Last-Translator: \n"
"Language-Team: Polish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: pl\n"
"X-Crowdin-File-ID: 670\n"
"Language: pl_PL\n"

#: redbot/cogs/audio/core/events/dpy.py:34
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Próbowałeś uruchomić serwer Audio Lavalink na nieobsługiwanej architekturze. Dostępne będą tylko komendy związane z ustawieniami."

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "No DJ role found. Disabling DJ mode."
msgstr "Nie znaleziono roli DJ. Wyłączanie trybu DJ."

#: redbot/cogs/audio/core/events/dpy.py:80
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr "`{user_input}` nie jest poprawną wartością dla `{command}`"

#: redbot/cogs/audio/core/events/dpy.py:86
msgid "Unable To Parse Argument"
msgstr "Nie można przeanalizować argumentu"

#: redbot/cogs/audio/core/events/dpy.py:96
#: redbot/cogs/audio/core/events/dpy.py:104
msgid "Invalid Argument"
msgstr "Nieprawidłowy argument"

#: redbot/cogs/audio/core/events/dpy.py:97
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr "Argument który podałeś dla `{}` jest nieprawidłowy: oczekiwałem/am `{}`."

#: redbot/cogs/audio/core/events/dpy.py:114
msgid "Invalid Environment"
msgstr "Nieprawidłowe środowisko"

#: redbot/cogs/audio/core/events/dpy.py:115
msgid "Connection to Lavalink has been lost."
msgstr "Połączenie z Lavalink zostało utracone."

#: redbot/cogs/audio/core/events/dpy.py:123
msgid "No Player Available"
msgstr "Brak dostępnego odtwarzacza"

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "The bot is not connected to a voice channel."
msgstr "Bot nie jest podłączony do kanału głosowego."

#: redbot/cogs/audio/core/events/dpy.py:132
#: redbot/cogs/audio/core/events/lavalink.py:83
msgid "Unable to Get Track"
msgstr "Nie można pobrać utworu"

#: redbot/cogs/audio/core/events/dpy.py:133
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr "W tej chwili nie mogę pobrać utworu z Lavalinka, spróbuj ponownie za kilka minut."

#: redbot/cogs/audio/core/events/lavalink.py:74
msgid "Couldn't get a valid track."
msgstr "Nie można uzyskać prawidłowego utworu."

#: redbot/cogs/audio/core/events/lavalink.py:84
msgid "I'm unable get a track from Lavalink at the moment, try again in a few minutes."
msgstr "W tej chwili nie mogę dostać utworu z Lavalinka, spróbuj ponownie za kilka minut."

#: redbot/cogs/audio/core/events/lavalink.py:106
msgid "Auto Play started."
msgstr "Automatyczne odtwarzanie rozpoczęte."

#: redbot/cogs/audio/core/events/lavalink.py:121
msgid "Now Playing"
msgstr "Teraz gram"

#: redbot/cogs/audio/core/events/lavalink.py:123
msgid "Track length: {length} | Requested by: {user}"
msgstr "Długość utworu: {length} | Żądany przez: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:144
msgid "Queue ended."
msgstr "Kolejka zakończona."

#: redbot/cogs/audio/core/events/lavalink.py:186
msgid "Multiple Errors Detected"
msgstr "Wykryto wiele błędów"

#: redbot/cogs/audio/core/events/lavalink.py:187
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Zamykanie odtwarzacza audio z powodu wykrycia wielu błędów. Jeśli to się powtarza, poinformuj właściciela bota, ponieważ moduł Audio może być tymczasowo niedostępny."

#: redbot/cogs/audio/core/events/lavalink.py:201
msgid "Track Stuck"
msgstr "Zacięty utwór"

#: redbot/cogs/audio/core/events/lavalink.py:202
msgid "Playback of the song has stopped due to an unexcepted error.\\n{error}"
msgstr "Odtwarzanie utworu zostało zatrzymane z powodu nieoczekiwanego błędu.\\n{error}"

#: redbot/cogs/audio/core/events/lavalink.py:208
msgid "Track Error"
msgstr "Błąd utworu"

